services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evadb
    ports:
      - "5432:5432"
    volumes:
      - ./:/app
